Fix subpath tenants integration with asgi servers
django-tenants/django-tenants pull request #822
Opened 2022-08-29 09:04 UTC by ey3ball

This fixes django-tenants/django-tenants#820 until a better method is found.
    
The root cause is that information stored on connections is not available on all contexts during the processing of a request. In WSGI mode a single thread is involved so this is not visible. In ASGI mode however some code execute in the context of the async event loop. This is because the connection handler stores information in a thread_critical variable as seen here https://github.com/django/django/blob/main/django/utils/connection.py#L41.
    
 A better method would be to use asgi.local with our own sharing policy instead instead of attaching to the connexion object.
    
Until that is settled (@lorinkoz has a prototype in https://github.com/lorinkoz/django-pgschemas/pull/120) this patch modifies urlconf management in the subpath middleware.

IO/connection operations which were previously done during resolve() are removed, which prevents the error from popping up in ASGI mode

The downside is that we're modifying that we're generating a new urlconf object for each tenant. Also, this fixes a particular subpath issue, but does not address the more general issue of using connection to store a state accross each request processing.

2023-08-31 20:32 UTC, ianmubangizi commented
This PR has been open for a while any reason as to why?

2024-05-07 09:17 UTC, atodorov requested changes

2024-05-29 16:46 UTC, ey3ball commented on django_tenants/tests/test_urlresolvers.py
> -class URLResolversTestCase(BaseTestCase):
That was quite some time ago, not sure why I removed them, they probably had to be rewritten. Agree this needs some level on testing.

2024-05-29 16:52 UTC, ey3ball commented
I don't use django-tenants anymore but maybe @cguinard-fbx or @amrqt would be interested in taking over ?

2024-07-16 09:42 UTC, McDonnellJoseph commented
@atodorov Are you still interested in merging these changes ? If so I have taken over the changes of this PR [here](https://github.com/django-tenants/django-tenants/pull/1067) and adapted the existing tests.

2026-08-03 21:10 UTC, tomturner commented
Doing a pass over the open PRs ahead of the 3.11.0 release, so this is a status update rather than a comment on the code quality.

We've accumulated six overlapping proposals for tenant routing — new middleware variants and competing subfolder/ASGI fixes. Rather than take some subset and end up with several partly-overlapping ways to route a tenant, the plan is to keep the middleware surface as it is for 3.11.0 and treat routing as one deliberate piece of work for 4.0. #1067 is the approach we intend to build on there, since it removes the per-resolution database query that the current `TenantPrefixPattern` performs.

Closing this one on that basis — not because the problem isn't real. If you're running the patch in production and want to make the case for it in the 4.0 discussion, please do comment on #1067; that's where the routing work will be coordinated.

Thanks for the contribution, and sorry it sat unmerged for so long.

2026-08-03 21:10 UTC, closed without merging