Pass arguments to subcommand when using call_comand and tenant_command
django-tenants/django-tenants pull request #990
Opened 2023-11-01 13:44 UTC by hexponent

Fixes #989

2023-12-02 14:02 UTC, hexponent commented
@tomturner What do you think about this?

2024-04-08 21:33 UTC, hexponent commented
@tomturner Please review

2024-04-16 08:30 UTC, atodorov requested changes
Can you add a test case exercising the new functionality?

2024-04-24 10:12 UTC, hexponent commented
@atodorov Added test case

2024-04-26 15:44 UTC, atodorov approved these changes
One small comment, otherwise LGTM

2024-04-26 16:53 UTC, hexponent commented on django_tenants/tests/test_commands.py
> +        ])
Yeah, I agree, I just wanted to omit using another `indent` option in test
Will fix it right away

2024-04-26 17:37 UTC, atodorov approved these changes

2024-04-26 17:37 UTC, atodorov commented
@tomturner any objections ?

2024-05-07 09:12 UTC, merged